### ISSUE TITLE
Issue with connect teamspeak servers

### ISSUE THREAD

**Issue by sogehelper** [hwdsl2/setup-ipsec-vpn#398] opened 2018-06-01 15:42 UTC
I have an issue, i can't connect any TeamSpeak 3 server when using VPN
Without vpn can normally.
How i cna help reproduce?

**Comment by sogehelper** [comment] 2018-06-01 16:21
TeamSpeak servers use 9987 (by default) UDP port to connect

**Comment by hwdsl2** [comment] 2018-06-01 16:58
@sogehelper Hello! The VPN server itself does not place restrictions on TCP or UDP ports. Maybe your VPS server provider have restrictions on outgoing traffic to port 9987. Check with them to see if this is the case.

**Comment by sogehelper** [comment] 2018-06-01 17:07
I'm already asked them.
They sayd they are not block that.

**Comment by hwdsl2** [comment] 2018-06-01 17:30
@sogehelper Hmm... I'm not really sure about this then. The VPN server in its default configuration should be forwarding TCP/UDP traffic without restrictions. Are you connecting to a TeamSpeak server on the Internet or on your local LAN?

Closing this as it is not an issue with the VPN scripts. Perhaps you can try an alternative such as OpenVPN [1]?

[1] https://github.com/Nyr/openvpn-install

**Closed by hwdsl2** 2018-06-01 17:30 UTC

**Comment by sogehelper** [comment] 2018-06-01 20:31
I got same issue on OpenVPN
Maybe some firewall issue?

**Comment by hwdsl2** [comment] 2018-06-01 20:45
@sogehelper Yes the issue is most likely with your VPS provider or firewall.

**Comment by sogehelper** [comment] 2018-06-01 21:15
```root@satont:~# iptables -nvL
Chain INPUT (policy ACCEPT 64 packets, 9026 bytes)
 pkts bytes target     prot opt in     out     source               destination
   19  2793 f2b-sshd   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 22
    0     0 DROP       udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:1701 policy match                                                       dir in pol none
    4   188 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate INVALID
  200 17697 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISH                                                      ED
    1   144 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 500,4500
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:1701 policy match                                                       dir in pol ipsec
    0     0 DROP       udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:1701

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate INVALID
    0     0 ACCEPT     all  --  ens3   ppp+    0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISH                                                      ED
    0     0 ACCEPT     all  --  ppp+   ens3    0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  ppp+   ppp+    192.168.42.0/24      192.168.42.0/24
    0     0 ACCEPT     all  --  ens3   *       0.0.0.0/0            192.168.43.0/24      ctstate RELATED,ESTABLISH                                                      ED
    0     0 ACCEPT     all  --  *      ens3    192.168.43.0/24      0.0.0.0/0
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 217 packets, 18355 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain f2b-sshd (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 REJECT     all  --  *      *       182.100.67.231       0.0.0.0/0            reject-with icmp-port-unr                                                      eachable
   19  2793 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0
```
is that rules ok?

**Comment by hwdsl2** [comment] 2018-06-01 21:30
@sogehelper The IPTables rules look fine.

**Comment by sogehelper** [comment] 2018-06-01 21:32
I'm connecting to Internet TeamSpeak servers, not LAN
But i can't connect to any TeamSpeak server.. My host insists that the case of VPN and my broken hands.. but.. idk
