### ISSUE TITLE
How can the server visit internal network?

### ISSUE THREAD

**Issue by Laruto** [hwdsl2/setup-ipsec-vpn#554] opened 2019-04-29 02:41 UTC
I developed ipsec-vpn on my server and connected to it. Then I found that the internal network can visit the server,but the server can't visit the internal network.
How can I do to solve this problem.

**Comment by hwdsl2** [comment] 2019-04-29 02:52
Duplicate of https://github.com/hwdsl2/docker-ipsec-vpn-server/issues/141. It is generally difficult for the VPN server to access the subnet behind the VPN client(s) (your use case). On the other hand, it is easier for the VPN client(s) to access the subnet behind the VPN server. See: "Access VPN server's subnet" [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#access-vpn-servers-subnet

**Closed by hwdsl2** 2019-04-29 02:52 UTC
