### ISSUE TITLE
vpnsetup.sh - whack: Pluto is not running (no "/run/pluto/pluto.ctl")

### ISSUE THREAD

**Issue by gspannu** [hwdsl2/setup-ipsec-vpn#919] opened 2021-01-26 20:00 UTC
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
vpnsetup.sh installation is successful but Pluto not running.
Pluto not running after installing on Mac mini running Raspberry OS desktop
You may also refer to my comment in Issue 911 [here](https://github.com/hwdsl2/setup-ipsec-vpn/issues/911#issuecomment-767794930).
```
Status of 'sudo ipsec verify'

Verifying installed system and configuration files

Version check and ipsec on-path                   	[OK]
Libreswan 4.1 (netkey) on 4.19.0-13-amd64
Checking for IPsec support in kernel              	[OK]
 NETKEY: Testing XFRM related proc values
         ICMP default/send_redirects              	[OK]
         ICMP default/accept_redirects            	[OK]
         XFRM larval drop                         	[OK]
Pluto ipsec.conf syntax                           	[OK]
Checking rp_filter                                	[OK]
Checking that pluto is running                    	[FAILED]
Checking 'ip' command                             	[OK]
Checking 'iptables' command                       	[OK]
Checking 'prelink' command does not interfere with FIPS	[OK]
Checking for obsolete ipsec.conf options          	[OK]

```

```
Status of sudo ipsec status
whack: Pluto is not running (no "/run/pluto/pluto.ctl")

```
```
uname -a
Linux mini 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux

```
**To Reproduce**

_1. Clean install of Raspberry Desktop OS on Mac Mini
2. Executed vpnsetup.sh (no modifications)_

**Expected behavior**
_Pluto should install & run_ 

**Logs**

**Server (please complete the following information)**
- OS: _Raspberry Desktop OS [Debian GNU/Linux 10 (buster)]_
- Hosting provider (if applicable): _Apple Mac Mini_

**Client (please complete the following information)**
- Device: n/a
- OS: n/a
- VPN mode: n/a

**Additional context**

cat /etc/os-release 
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```
Status of sudo ipsec status
`whack: Pluto is not running (no "/run/pluto/pluto.ctl")`

**Comment by hwdsl2** [comment] 2021-01-27 04:02
@gspannu Thank you for reporting this issue. To help identify the error, can you post the (redacted) Libreswan logs?
```
sudo grep pluto /var/log/auth.log
```

**Comment by hwdsl2** [comment] 2021-01-27 06:48
@gspannu I have reproduced this issue on a Raspberry Pi Desktop OS. Here are the errors in the Libreswan logs:
```
pluto[PID]: Using Linux XFRM/NETKEY IPsec kernel support code on 4.19.0-13-amd64.
pluto[PID]: ERROR: netlink XFRM_MSG_UPDPOLICY response for flow add port bypass included errno 95: Operation not supported
pluto[PID]: ERROR: netlink XFRM_MSG_UPDPOLICY response for flow add port bypass included errno 95: Operation not supported
pluto[PID]: Could not add the ICMP bypass policies
pluto[PID]: seccomp security for helper not supported
pluto[PID]: 1 helper threads shutdown
pluto[PID]: ABORT: ASSERTION FAILED: event_initialized(&se->ev) (in free_signal_handlers() at server.c:448)
```

This is a special case because Raspberry Pi Desktop runs a 64-bit kernel with 32-bit userland programs [1][2], which results in Libreswan crashing.

**Workaround:** Install the 32-bit PAE kernel for Raspberry Pi Desktop on your Mac mini, by running:
```
sudo apt-get update
sudo apt-get install linux-image-686-pae linux-headers-686-pae
```

After that, reboot into the 32-bit kernel and re-run the VPN setup scripts.

Closing because this is a special case with 64-bit kernel / 32-bit userland, which the VPN setup script cannot currently handle. You may want to instead file an issue at https://github.com/libreswan/libreswan to see if a better solution is available.

cc: @letoams

[1] https://www.raspberrypi.org/forums/viewtopic.php?t=278088
[2] https://unix.stackexchange.com/a/134393

**Closed by hwdsl2** 2021-01-27 06:48 UTC

**Comment by gspannu** [comment] 2021-01-27 11:29
> @gspannu I have reproduced this issue on a Raspberry Pi Desktop OS. Here are the errors in the Libreswan logs:

> **Workaround:** Install the 32-bit PAE kernel for Raspberry Pi Desktop on your Mac mini, by running:
> 
> ```
> sudo apt-get update
> sudo apt-get install linux-image-686-pae linux-headers-686-pae
> ```
> 
> After that, reboot into the 32-bit kernel and re-run the VPN setup scripts.

You are an absolute star ⭐️⭐️⭐️⭐️⭐️
Trying this out as I write... will verify and confirm back.

**Comment by gspannu** [comment] 2021-01-27 22:30
**Checked, all working now after installing the 32-bit PAE kernel.** 🙏

Quick question: Will I need to do the same for Ubuntu running on Mac Mini or is this necessary only for Raspberry OS running on a Mac Mini?

Thank you for your support, much appreciated...

**Comment by hwdsl2** [comment] 2021-01-28 00:37
@gspannu This workaround is only necessary for Raspberry Pi Desktop OS running a 64-bit kernel with 32-bit userland.
