### ISSUE TITLE
Setup IKEv2/Windows 10

### ISSUE THREAD

**Issue by evil-shrike** [hwdsl2/setup-ipsec-vpn#106] opened 2017-01-26 01:58 UTC
Hi.
Sorry, but let me ask one more question. I'm trying to get IKEv2 working with Windows10 client. 
I followed the [How-To: IKEv2 VPN for Windows 7 and newer](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md).

Connection fails with error "IKE failed to find valid machine certificate". Server logs (`grep pluto /var/log/auth.log`) (2.2.2.2 - is the Win10 machine):
```
Jan 26 00:43:01 VPN pluto[5221]: packet from 2.2.2.2:500: ignoring unknown Vendor ID payload [01528bbbc00696121849ab9a1c5b2a5100000002]
Jan 26 00:43:01 VPN pluto[5221]: packet from 2.2.2.2:500: ikev2-cp IKE proposals for initial responder: 1:IKE:ENCR=3DES;PRF=HMAC_SHA1;INTEG=HMAC_SHA1_96;DH=MODP2048 2:IKE:ENCR=3DES;PRF=HMAC_SHA1;INTEG=HMAC_SHA1_96;DH=MODP1024 3:IKE:ENCR=AES_CBC_256,AES_CBC_128;PRF=HMAC_SHA1;INTEG=HMAC_SHA1_96;DH=MODP2048 4:IKE:ENCR=AES_CBC_256,AES_CBC_128;PRF=HMAC_SHA1;INTEG=HMAC_SHA1_96;DH=MODP1024 5:IKE:ENCR=AES_CBC_256,AES_CBC_128;PRF=HMAC_SHA2_256;INTEG=HMAC_SHA2_256_128;DH=MODP2048 6:IKE:ENCR=AES_CBC_256,AES_CBC_128;PRF=HMAC_SHA2_256;INTEG=HMAC_SHA2_256_128;DH=MODP1024
Jan 26 00:43:01 VPN pluto[5221]: packet from 2.2.2.2:500: proposal 1:IKE:ENCR=AES_CBC_256;PRF=HMAC_SHA1;INTEG=HMAC_SHA1_96;DH=MODP2048 chosen from: 1:IKE:ENCR=AES_CBC_256;INTEG=HMAC_SHA1_96;PRF=HMAC_SHA1;DH=MODP2048[first-match] 2:IKE:ENCR=AES_CBC_256;INTEG=HMAC_SHA2_256_128;PRF=HMAC_SHA2_256;DH=MODP2048 3:IKE:ENCR=AES_CBC_256;INTEG=HMAC_SHA2_384_192;PRF=HMAC_SHA2_384;DH=MODP2048
Jan 26 00:43:01 VPN pluto[5221]: "ikev2-cp"[5] 2.2.2.2 #11: STATE_PARENT_R1: received v2I1, sent v2R1 {auth=IKEv2 cipher=aes_256 integ=sha1_96 prf=sha group=MODP2048}
Jan 26 00:43:01 VPN pluto[5221]: packet from 2.2.2.2:500: ignoring unknown Vendor ID payload [01528bbbc00696121849ab9a1c5b2a5100000002]
Jan 26 00:43:01 VPN pluto[5221]: packet from 2.2.2.2:500: proposal 1:IKE:ENCR=AES_CBC_256;PRF=HMAC_SHA1;INTEG=HMAC_SHA1_96;DH=MODP2048 chosen from: 1:IKE:ENCR=AES_CBC_256;INTEG=HMAC_SHA1_96;PRF=HMAC_SHA1;DH=MODP2048[first-match] 2:IKE:ENCR=AES_CBC_256;INTEG=HMAC_SHA2_256_128;PRF=HMAC_SHA2_256;DH=MODP2048 3:IKE:ENCR=AES_CBC_256;INTEG=HMAC_SHA2_384_192;PRF=HMAC_SHA2_384;DH=MODP2048
Jan 26 00:43:01 VPN pluto[5221]: "ikev2-cp"[5] 2.2.2.2 #12: STATE_PARENT_R1: received v2I1, sent v2R1 {auth=IKEv2 cipher=aes_256 integ=sha1_96 prf=sha group=MODP2048}
Jan 26 00:43:01 VPN pluto[5221]: packet from 2.2.2.2:500: sending unencrypted notification v2N_INVALID_IKE_SPI to 2.2.2.2:500
```
It looks like client and server cannot negotiate about encryption algorithms(?)

* the VPN set up to use machine cert (no user/pwd)
* downloaded and installed certificates into Machine/TrustedRoots store (double checked) (also tried to separate CA and client cert between Personal/TrustedRoots in Machine)
* ipsec seems good:
```
root@VPN:~# ipsec verify
Verifying installed system and configuration files

Version check and ipsec on-path                         [OK]
Libreswan 3.19 (netkey) on 4.8.14-std-2
Checking for IPsec support in kernel                    [OK]
 NETKEY: Testing XFRM related proc values
         ICMP default/send_redirects                    [OK]
         ICMP default/accept_redirects                  [OK]
         XFRM larval drop                               [OK]
Pluto ipsec.conf syntax                                 [OK]
Two or more interfaces found, checking IP forwarding    [OK]
Checking rp_filter                                      [OK]
Checking that pluto is running                          [OK]
 Pluto listening for IKE on udp 500                     [OK]
 Pluto listening for IKE/NAT-T on udp 4500              [OK]
 Pluto ipsec.secret syntax                              [OK]
Checking 'ip' command                                   [OK]
Checking 'iptables' command                             [OK]
Checking 'prelink' command does not interfere with FIPS [OK]
Checking for obsolete ipsec.conf options                [OK]
```
* certs are in place:
```
Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

Example CA                                                   CTu,u,u
1.1.1.1                                                 u,u,u
vpnclient                                                    u,u,u
```
* registry fix for RasMan's NegotiateDH2048_AES256(2) applied
* client/server rebooted
* tried creating VPN connection via PowerShell:
```
Add-VpnConnection -Name "IKEv2" -ServerAddress "1.1.1.1" -TunnelType IKEv2 -AuthenticationMethod MachineCertificate -AllUserConnection

PS C:\Windows\system32> Set-VpnConnectionIPsecConfiguration -ConnectionName "IKEv2" -AuthenticationTransformConstants None -CipherTransformConstants AES256 -EncryptionMethod AES256 -IntegrityCheckMethod SHA256 -DHGroup Group14 -PfsGroup None -PassThru -AllUserConnection


AuthenticationTransformConstants : None
CipherTransformConstants         : AES256
DHGroup                          : Group14
IntegrityCheckMethod             : SHA256
PfsGroup                         : None
EncryptionMethod                 : AES256
```
It didn't change anything (at least after registry fix for RasMan applied)

**Also after I setup IKEv2 L2TP/IPSec stop working. Is it normal?**
Here's server log (`grep pluto /var/log/auth.log`):
```
Jan 26 01:00:03 VPN pluto[5221]: packet from 2.2.2.2:500: ignoring unknown Vendor ID payload [01528bbbc00696121849ab9a1c5b2a5100000001]
Jan 26 01:00:03 VPN pluto[5221]: packet from 2.2.2.2:500: initial Main Mode message received on 10.10.10.10:500 but no connection has been authorized with policy PSK+IKEV1_ALLOW
Jan 26 01:00:04 VPN pluto[5221]: packet from 2.2.2.2:500: ignoring unknown Vendor ID payload [01528bbbc00696121849ab9a1c5b2a5100000001]
Jan 26 01:00:04 VPN pluto[5221]: packet from 2.2.2.2:500: initial Main Mode message received on 10.10.10.10:500 but no connection has been authorized with policy PSK+IKEV1_ALLOW
Jan 26 01:00:05 VPN pluto[5221]: packet from 2.2.2.2:500: ignoring unknown Vendor ID payload [01528bbbc00696121849ab9a1c5b2a5100000001]
Jan 26 01:00:05 VPN pluto[5221]: packet from 2.2.2.2:500: initial Main Mode message received on 10.10.10.10:500 but no connection has been authorized with policy PSK+IKEV1_ALLOW
```

**Comment by hwdsl2** [comment] 2017-01-26 03:53
@evil-shrike Hello! Please verify that you have imported the client certificate into the Computer certificate store and not the Local user store. Please see [1] [2]. You must choose "Computer account".

[1] https://libreswan.org/wiki/VPN_server_for_remote_clients_using_IKEv2#Common_Windows_7_client_errors
[2] https://wiki.strongswan.org/projects/strongswan/wiki/Win7Certs

**Comment by hwdsl2** [comment] 2017-01-26 06:22
@evil-shrike To add to my previous reply... The client certificate must be placed under "Personal" folder, while the CA certificate must be placed in "Trusted Root". As I said earlier, double check that you added the "Computer account" certificate snap-in.

If you tried connecting using IKEv2, you must either wait a few minutes or restart the IPsec service on the VPN server (service ipsec restart), before switching to  IPsec/L2TP.

**Comment by evil-shrike** [comment] 2017-01-26 07:59
@hwdsl2 sure, checked it many times. 
As on importing I get two certs at once in the same location I tried (all in Local machine):
* import p12-cert into TrustedRoots
* import p12-cert into TrustedRoots, delete client, import p12-cert into Personal, delete CA in Personal

![image](https://cloud.githubusercontent.com/assets/1203230/22323691/9879293e-e3b5-11e6-9010-6a2bb5653073.png)


As for L2TP.
> If you tried connecting using IKEv2, you must either wait a few minutes or restart the IPsec service on the VPN server (service ipsec restart), before switching to IPsec/L2TP.

I waited. I do see that server tear down connections:
```
Jan 26 07:52:42 VPN pluto[5221]: "ikev2-cp"[10] 2.2.2.2 #27: deleting state (STATE_PARENT_R1)
Jan 26 07:52:42 VPN pluto[5221]: "ikev2-cp"[10] 2.2.2.2 #28: deleting state (STATE_PARENT_R1)
Jan 26 07:52:42 VPN pluto[5221]: "ikev2-cp"[10] 2.2.2.2: deleting connection "ikev2-cp"[10] 2.2.2.2 instance with peer 2.2.2.2 {isakmp=#0/ipsec=#0}
```
then tried to connect via L2TP.
Also tried restart service and connect via L2TP. It hangs with mentioned above log on the server.

**Comment by hwdsl2** [comment] 2017-01-26 16:34
@evil-shrike Thanks for the update. I tried but was unable to reproduce this issue. Here are some other things to try:

1. Check your `ipsec.conf` for any duplicate `ikev2-cp` sections, and remove any if found. Restart services with:   
   service ipsec restart
   service xl2tpd restart
2. Try removing the NegotiateDH2048_AES256 registry key and reboot your PC.
3. The IKEv2 VPN may not work on some networks, because the built-in Windows VPN client does not support IKEv2 fragmentation. Try the registry fix for "Error 809" in https://git.io/vpnclients If it still does not work, make a backup, remove the entire `ikev2-cp` section from `ipsec.conf` and restart services. You should now be able to connect using L2TP/IPsec.

**Comment by hwdsl2** [comment] 2017-01-26 18:45
@evil-shrike Hello! I have just managed to reproduced this issue on a Windows Server 2012 machine. I'll see if I can find a solution.

**Comment by hwdsl2** [comment] 2017-01-26 19:45
@evil-shrike Unfortunately I was unable to get IKEv2 work on Windows Server 2012, due to error "Error 13806: IKE failed to find valid machine certificate..." Note that my tests on Windows 7 had been successful. Currently I don't have the time to look into this further. I would suggest that you remove the client and CA certificates from the Windows machine, restart the ipsec/xl2tpd services, and use the IPsec/L2TP or Cisco IPsec mode to connect.

Thanks again for bringing this issue to my attention.

**Comment by hwdsl2** [comment] 2017-01-26 21:07
@evil-shrike OK I figured it out. For some reason, Windows Server 2012 (and possibly others) requires that the IKEv2 machine certificate contain the "Client Auth" EKU, in addition to "Server Auth". Please generate a new client certificate on the VPN server. Follow these revised steps:

```
$ certutil -S -c "Example CA" -n "vpnclient-new" -s "O=Example,CN=vpnclient-new" -k rsa -g 4096 -v 36 -d sql:/etc/ipsec.d -t ",," -1 -6 -8 "vpnclient-new"

A random seed must be generated that will be used in the
creation of your key.  One of the easiest ways to create a
random seed is to use the timing of keystrokes on a keyboard.

To begin, type keys on the keyboard until this progress meter
is full.  DO NOT USE THE AUTOREPEAT FUNCTION ON YOUR KEYBOARD!

Continue typing until the progress meter is full:

|************************************************************|

Finished.  Press enter to continue:

Generating key.  This may take a few moments...

               0 - Digital Signature
               1 - Non-repudiation
               2 - Key encipherment
               3 - Data encipherment
               4 - Key agreement
               5 - Cert signing key
               6 - CRL signing key
               Other to finish
> 0
               0 - Digital Signature
               1 - Non-repudiation
               2 - Key encipherment
               3 - Data encipherment
               4 - Key agreement
               5 - Cert signing key
               6 - CRL signing key
               Other to finish
> 2
               0 - Digital Signature
               1 - Non-repudiation
               2 - Key encipherment
               3 - Data encipherment
               4 - Key agreement
               5 - Cert signing key
               6 - CRL signing key
               Other to finish
> 8
Is this a critical extension [y/N]?
N
               0 - Server Auth
               1 - Client Auth
               2 - Code Signing
               3 - Email Protection
               4 - Timestamp
               5 - OCSP Responder
               6 - Step-up
               7 - Microsoft Trust List Signing
               Other to finish
> 0
               0 - Server Auth
               1 - Client Auth
               2 - Code Signing
               3 - Email Protection
               4 - Timestamp
               5 - OCSP Responder
               6 - Step-up
               7 - Microsoft Trust List Signing
               Other to finish
> 1
               0 - Server Auth
               1 - Client Auth
               2 - Code Signing
               3 - Email Protection
               4 - Timestamp
               5 - OCSP Responder
               6 - Step-up
               7 - Microsoft Trust List Signing
               Other to finish
> 8
Is this a critical extension [y/N]?
N
```

Export the new certificate and key:
```
$ pk12util -o vpnclient-new.p12 -n "vpnclient-new" -d sql:/etc/ipsec.d

Enter password for PKCS12 file:
Re-enter password:
pk12util: PKCS12 EXPORT SUCCESSFUL
```

Restart IPsec service:
```
service ipsec restart
```

The generated `vpnclient-new.p12` file should then be securely transferred to the VPN client device and imported (as you did earlier). Remove any old certificates first. The IKEv2 VPN should work after that.

**Closed by hwdsl2** 2017-01-26 21:07 UTC

**Comment by evil-shrike** [comment] 2017-01-26 21:43
@hwdsl2 hello! Thanks for your help! It was definitely the reason - as I regenerated certificate (removed old one), downloaded, installed (Personal/TRoots in Machine) the error has gone.
But now I'm getting a different error - 809 (before it was 13806):
![image](https://cloud.githubusercontent.com/assets/1203230/22351068/590fce84-e427-11e6-831f-099c154a3851.png)

In [troubleshooting-common-vpn-related-errors](https://blogs.technet.microsoft.com/rrasblog/2009/08/12/troubleshooting-common-vpn-related-errors/) it's mentioned that : 
>Error Description: 809: The network connection between your computer and the VPN server could not be established because the remote server is not responding. This could be because one of the network devices (e.g, firewalls, NAT, routers, etc) between your computer and the remote server is not configured to allow VPN connections. Please contact your Administrator or your service provider to determine which device may be causing the problem.
>
>Possible Cause: This error usually comes when some firewall between client and server is blocking the ports used by VPN tunnel
>
> L2TP or IKEv2 port (UDP port 500, UDP port 4500) is blocked by a firewall/router. [Applicable to tunnel type = L2TP or IKEv2]

* tried disabling Firewall
* Registry fix AssumeUDPEncapsulationContextOnSendRule applied
* In my router I have "IPSec Passthrough" enabled:
![image](https://cloud.githubusercontent.com/assets/1203230/22351516/6806a528-e429-11e6-9bf5-83c9e38144d0.png)

I looks like a client issue, as the last line in log is:
```
Jan 26 21:29:16 VPN pluto[12099]: "ikev2-cp"[3] 2.2.2.2 #3: STATE_PARENT_R1: received v2I1, sent v2R1 {auth=IKEv2 cipher=3des_cbc_192 integ=sha1_96 prf=sha group=MODP1024}
```

**Comment by evil-shrike** [comment] 2017-01-26 22:52
I also tried to connect from Android phone (v60.0.1/builtin client) as through 4G and through my router. It connected to VPN (I can see "negotiated connection" in server log) but it's not working (no IP acquired and no traffic).

**Comment by hwdsl2** [comment] 2017-01-26 23:01
@evil-shrike Thanks for the update. Do you have more server logs to share? And did you restore the IPTables rules? They are required for the VPN to work. Try rebooting both your server and Windows computer.

You may have encountered "Error 809" because of IKEv2 fragmentation. As mentioned in the docs, the Windows built-in IKEv2 client does not support IKEv2 fragmentation. This can lead to connection errors on some networks, due to the large UDP packets containing the certificates being dropped by routers. This is a known issue.

**Comment by evil-shrike** [comment] 2017-01-26 23:31
Win10 machine is connecting (failing with "Error 809"):
```
Jan 26 23:22:22 VPN pluto[4905]: packet from 3.3.3.3:59688: ignoring unknown Vendor ID payload [01528bbbc00696121849ab9a1c5b2a5100000002]
Jan 26 23:22:22 VPN pluto[4905]: packet from 3.3.3.3:59688: ikev2-cp IKE proposals for initial responder: 1:IKE:ENCR=3DES;PRF=HMAC_SHA1;INTEG=HMAC_SHA1_96;DH=MODP2048 2:IKE:ENCR=3DES;PRF=HMAC_SHA1;INTEG=HMAC_SHA1_96;DH=MODP1024 3:IKE:ENCR=AES_CBC_256,AES_CBC_128;PRF=HMAC_SHA1;INTEG=HMAC_SHA1_96;DH=MODP2048 4:IKE:ENCR=AES_CBC_256,AES_CBC_128;PRF=HMAC_SHA1;INTEG=HMAC_SHA1_96;DH=MODP1024 5:IKE:ENCR=AES_CBC_256,AES_CBC_128;PRF=HMAC_SHA2_256;INTEG=HMAC_SHA2_256_128;DH=MODP2048 6:IKE:ENCR=AES_CBC_256,AES_CBC_128;PRF=HMAC_SHA2_256;INTEG=HMAC_SHA2_256_128;DH=MODP1024
Jan 26 23:22:22 VPN pluto[4905]: packet from 3.3.3.3:59688: proposal 1:IKE:ENCR=3DES;PRF=HMAC_SHA1;INTEG=HMAC_SHA1_96;DH=MODP1024 chosen from: 1:IKE:ENCR=3DES;INTEG=HMAC_SHA1_96;PRF=HMAC_SHA1;DH=MODP1024[first-match] 2:IKE:ENCR=3DES;INTEG=HMAC_SHA2_256_128;PRF=HMAC_SHA2_256;DH=MODP1024 3:IKE:ENCR=3DES;INTEG=HMAC_SHA2_384_192;PRF=HMAC_SHA2_384;DH=MODP1024 4:IKE:ENCR=AES_CBC_128;INTEG=HMAC_SHA1_96;PRF=HMAC_SHA1;DH=MODP1024 5:IKE:ENCR=AES_CBC_128;INTEG=HMAC_SHA2_256_128;PRF=HMAC_SHA2_256;DH=MODP1024 6:IKE:ENCR=AES_CBC_128;INTEG=HMAC_SHA2_384_192;PRF=HMAC_SHA2_384;DH=MODP1024 7:IKE:ENCR=AES_CBC_192;INTEG=HMAC_SHA1_96;PRF=HMAC_SHA1;DH=MODP1024 8:IKE:ENCR=AES_CBC_192;INTEG=HMAC_SHA2_256_128;PRF=HMAC_SHA2_256;DH=MODP1024 9:IKE:ENCR=AES_CBC_192;INTEG=HMAC_SHA2_384_192;PRF=HMAC_SHA2_384;DH=MODP1024 10:IKE:ENCR=AES_CBC_256;INTEG=HMAC_SHA1_96;PRF=HMAC_SHA1;DH=MODP1024 11:IKE:ENCR=AES_CBC_256;INTEG=HMAC_SHA2_256_128;PRF=HMAC_SHA2_256;DH=MODP1024 12:IKE:ENCR=AES_CBC_256;INTEG=HMAC_SHA2_384_192;PRF=HMAC_SHA2_384;DH=MODP1024
Jan 26 23:22:22 VPN pluto[4905]: "ikev2-cp"[12] 3.3.3.3 #16: STATE_PARENT_R1: received v2I1, sent v2R1 {auth=IKEv2 cipher=3des_cbc_192 integ=sha1_96 prf=sha group=MODP1024}
```

> And did you restore the IPTables rules? They are required for the VPN to work

No! What rules? I can't see anything about that in the [doc](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md) :( 

> This can lead to connection errors on some networks, due to the large UDP packets containing the certificates being dropped by routers. 

I tried connecting (from Win10) through my Android's hotspot (4G) (i.e. without router) - the same result.

**Comment by hwdsl2** [comment] 2017-01-26 23:38
@evil-shrike Sorry I misunderstood when you said "disable firewall". There is no extra IPTables rules for IKEv2. As long as you did not flush the IPTables rules created by the VPN setup script, you should be fine.

Can you try the strongSwan Android VPN client? It supports IKEv2 only and you can import the `.p12` file directly into the app, then create a VPN connection based on certificate authentication.

**Comment by evil-shrike** [comment] 2017-01-27 00:20
@hwdsl2 sorry, it wasn't clear, yeah I meant client Windows firewall.

> strongSwan Android failed to connected (using already imported my certificates):
```
Jan 27 03:00:50 00[DMN] Starting IKE charon daemon (strongSwan 5.5.2dr3, Linux 3.10.9-9186796, armv7l)
Jan 27 03:00:50 00[LIB] loaded plugins: androidbridge charon android-log openssl fips-prf random nonce pubkey chapoly curve25519 pkcs1 pkcs8 pem xcbc hmac socket-default eap-identity eap-mschapv2 eap-md5 eap-gtc eap-tls
Jan 27 03:00:50 00[JOB] spawning 16 worker threads
Jan 27 03:00:50 08[CFG] loaded user certificate 'CN=vpnclient-new, O=Example' and private key
Jan 27 03:00:50 08[CFG] loaded CA certificate 'CN=Example CA, O=Example'
Jan 27 03:00:50 08[IKE] initiating IKE_SA android[1] to 1.1.1.1
Jan 27 03:00:50 08[ENC] generating IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(REDIR_SUP) ]
Jan 27 03:00:50 08[NET] sending packet: from 10.41.250.20[58623] to 1.1.1.1[500] (746 bytes)
Jan 27 03:00:50 10[NET] received packet: from 1.1.1.1[500] to 10.41.250.20[58623] (40 bytes)
Jan 27 03:00:50 10[ENC] parsed IKE_SA_INIT response 0 [ N(INVAL_KE) ]
Jan 27 03:00:50 10[IKE] peer didn't accept DH group ECP_256, it requested MODP_2048
Jan 27 03:00:50 10[IKE] initiating IKE_SA android[1] to 1.1.1.1
Jan 27 03:00:50 10[ENC] generating IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(REDIR_SUP) ]
Jan 27 03:00:50 10[NET] sending packet: from 10.41.250.20[58623] to 1.1.1.1[500] (938 bytes)
Jan 27 03:00:50 11[NET] received packet: from 1.1.1.1[500] to 10.41.250.20[58623] (461 bytes)
Jan 27 03:00:50 11[ENC] parsed IKE_SA_INIT response 0 [ SA KE No N(FRAG_SUP) N(NATD_S_IP) N(NATD_D_IP) CERTREQ ]
Jan 27 03:00:51 11[IKE] local host is behind NAT, sending keep alives
Jan 27 03:00:51 11[IKE] remote host is behind NAT
Jan 27 03:00:51 11[IKE] received cert request for "CN=Example CA, O=Example"
[skipped]
Jan 27 03:00:51 11[IKE] sending cert request for "CN=Example CA, O=Example"
Jan 27 03:00:52 11[IKE] authentication of 'CN=vpnclient-new, O=Example' (myself) with RSA signature successful
Jan 27 03:00:52 11[IKE] sending end entity cert "CN=vpnclient-new, O=Example"
Jan 27 03:00:52 11[IKE] establishing CHILD_SA android
Jan 27 03:00:52 11[ENC] generating IKE_AUTH request 1 [ IDi CERT N(INIT_CONTACT) CERTREQ AUTH CPRQ(ADDR ADDR6 DNS DNS6) N(ESP_TFC_PAD_N) SA TSi TSr N(MOBIKE_SUP) N(NO_ADD_ADDR) N(EAP_ONLY) ]
Jan 27 03:00:52 11[ENC] splitting IKE message with length of 5468 bytes into 5 fragments
Jan 27 03:00:52 11[ENC] generating IKE_AUTH request 1 [ EF(1/5) ]
Jan 27 03:00:52 11[ENC] generating IKE_AUTH request 1 [ EF(2/5) ]
Jan 27 03:00:52 11[ENC] generating IKE_AUTH request 1 [ EF(3/5) ]
Jan 27 03:00:52 11[ENC] generating IKE_AUTH request 1 [ EF(4/5) ]
Jan 27 03:00:52 11[ENC] generating IKE_AUTH request 1 [ EF(5/5) ]
Jan 27 03:00:52 11[NET] sending packet: from 10.41.250.20[41676] to 1.1.1.1[4500] (1368 bytes)
Jan 27 03:00:52 11[NET] sending packet: from 10.41.250.20[41676] to 1.1.1.1[4500] (1368 bytes)
Jan 27 03:00:52 11[NET] sending packet: from 10.41.250.20[41676] to 1.1.1.1[4500] (1368 bytes)
Jan 27 03:00:52 11[NET] sending packet: from 10.41.250.20[41676] to 1.1.1.1[4500] (1368 bytes)
Jan 27 03:00:52 11[NET] sending packet: from 10.41.250.20[41676] to 1.1.1.1[4500] (224 bytes)
Jan 27 03:00:53 14[NET] received packet: from 1.1.1.1[4500] to 10.41.250.20[41676] (536 bytes)
Jan 27 03:00:53 14[ENC] parsed IKE_AUTH response 1 [ EF(1/5) ]
Jan 27 03:00:53 14[ENC] received fragment #1 of 5, waiting for complete IKE message
Jan 27 03:00:53 15[NET] received packet: from 1.1.1.1[4500] to 10.41.250.20[41676] (536 bytes)
Jan 27 03:00:53 15[ENC] parsed IKE_AUTH response 1 [ EF(2/5) ]
Jan 27 03:00:53 15[ENC] received fragment #2 of 5, waiting for complete IKE message
Jan 27 03:00:53 08[NET] received packet: from 1.1.1.1[4500] to 10.41.250.20[41676] (536 bytes)
Jan 27 03:00:53 08[ENC] parsed IKE_AUTH response 1 [ EF(3/5) ]
Jan 27 03:00:53 08[ENC] received fragment #3 of 5, waiting for complete IKE message
Jan 27 03:00:53 16[NET] received packet: from 1.1.1.1[4500] to 10.41.250.20[41676] (536 bytes)
Jan 27 03:00:53 16[ENC] parsed IKE_AUTH response 1 [ EF(4/5) ]
Jan 27 03:00:53 16[ENC] received fragment #4 of 5, waiting for complete IKE message
Jan 27 03:00:53 09[NET] received packet: from 1.1.1.1[4500] to 10.41.250.20[41676] (112 bytes)
Jan 27 03:00:53 09[ENC] parsed IKE_AUTH response 1 [ EF(5/5) ]
Jan 27 03:00:53 09[ENC] received fragment #5 of 5, reassembling fragmented IKE message
Jan 27 03:00:53 09[ENC] parsed IKE_AUTH response 1 [ IDr CERT AUTH CPRP(ADDR DNS DNS) SA TSi TSr ]
Jan 27 03:00:53 09[IKE] received end entity cert "CN=1.1.1.1, O=Example"
Jan 27 03:00:53 09[CFG]   using certificate "CN=1.1.1.1, O=Example"
Jan 27 03:00:53 09[CFG]   using trusted ca certificate "CN=Example CA, O=Example"
Jan 27 03:00:53 09[CFG]   reached self-signed root ca with a path length of 0
Jan 27 03:00:53 09[IKE] authentication of '1.1.1.1' with RSA signature successful
Jan 27 03:00:53 09[CFG] constraint check failed: identity '1.1.1.1' required 
Jan 27 03:00:53 09[CFG] selected peer config 'android' inacceptable: constraint checking failed
Jan 27 03:00:53 09[CFG] no alternative config found
Jan 27 03:00:53 09[ENC] generating INFORMATIONAL request 2 [ N(AUTH_FAILED) ]
Jan 27 03:00:53 09[NET] sending packet: from 10.41.250.20[41676] to 1.1.1.1[4500] (68 bytes)
```

But anyway as LibreSwap can't support several IPsec and IKEv2 sessions simultaneously ("no connection has been authorized with policy PSK+IKEV1_ALLOW") and I can't get my Win10 machine working via IKEv2 I have to rollback to IPsec or OpenVPN (I mean it's not much sense to have only Android working via IKEv2).

Maybe I'll try on Win7 some time later..

Anyway big thanks for spending your time and helping!

BTW: May I ask why did you choose LibreSwap and not strongSwan? The latter seems to be a bit more popular, doesn't?

**Comment by hwdsl2** [comment] 2017-01-27 00:29
@evil-shrike Thanks for the update. Choosing Libreswan was just because I had been using Openswan for my personal VPN, and Libreswan was created as a fork to Openswan, which has been more actively developed. I think strongSwan is also very good, with a large community :)
