### ISSUE TITLE
在syslog中有这样的日志“Can not find tunnel ” 是什么原因？

### ISSUE THREAD

**Issue by hookybaby** [hwdsl2/setup-ipsec-vpn#17] opened 2016-05-03 10:01 UTC
May  3 17:28:06 iZ23g1qi4a3Z xl2tpd[1402]: Can not find tunnel 55415 (refhim=0)
May  3 17:28:06 iZ23g1qi4a3Z xl2tpd[1402]: network_thread: unable to find call or tunnel to handle packet.  call = 21990, tunnel = 55415 Dumping.

**Comment by hwdsl2** [comment] 2016-05-03 20:38
@hookybaby 请问VPN是否工作正常？还是有遇到连接问题？

**Comment by hwdsl2** [comment] 2016-05-05 20:43
@hookybaby Closing this issue for now. Feel free to reply with more information if the problem persists.

**Closed by hwdsl2** 2016-05-05 20:43 UTC

**Comment by larryisthere** [comment] 2016-09-21 07:05
我也遇到这个问题，syslog 里报错失这样的：

> Sep 21 06:49:11 larryzh xl2tpd[4757]: Can not find tunnel 11598 (refhim=0)
> Sep 21 06:49:11 larryzh xl2tpd[4757]: network_thread: unable to find call or tunnel to handle packet.  call = 60108, tunnel = 11598 Dumping.
> Sep 21 06:49:11 larryzh xl2tpd[4757]: Can not find tunnel 11598 (refhim=0)
> Sep 21 06:49:11 larryzh xl2tpd[4757]: network_thread: unable to find call or tunnel to handle packet.  call = 60108, tunnel = 11598 Dumping.
> Sep 21 06:49:11 larryzh xl2tpd[4757]: Can not find tunnel 11598 (refhim=0)
> Sep 21 06:49:11 larryzh xl2tpd[4757]: network_thread: unable to find call or tunnel to handle packet.  call = 60108, tunnel = 11598 Dumping.
> Sep 21 06:49:12 larryzh xl2tpd[4757]: Can not find tunnel 11598 (refhim=0)
> Sep 21 06:49:12 larryzh xl2tpd[4757]: network_thread: unable to find call or tunnel to handle packet.  call = 60108, tunnel = 11598 Dumping.
> Sep 21 06:49:12 larryzh xl2tpd[4757]: Can not find tunnel 11598 (refhim=0)
> Sep 21 06:49:12 larryzh xl2tpd[4757]: network_thread: unable to find call or tunnel to handle packet.  call = 60108, tunnel = 11598 Dumping.
> Sep 21 06:49:12 larryzh xl2tpd[4757]: Can not find tunnel 11598 (refhim=0)
> Sep 21 06:49:12 larryzh xl2tpd[4757]: network_thread: unable to find call or tunnel to handle packet.  call = 60108, tunnel = 11598 Dumping.

能连上vpn，但所有连接都建立不了，包括本来已经连上的qq也会断开，网页也打不开。
运行 ipsec verify 是

> Verifying installed system and configuration files
> 
> Version check and ipsec on-path                   	[OK]
> Libreswan 3.18 (netkey) on 3.18.5-x86-linode70
> Checking for IPsec support in kernel              	[OK]
>  NETKEY: Testing XFRM related proc values
>          ICMP default/send_redirects              	[OK]
>          ICMP default/accept_redirects            	[OK]
>          XFRM larval drop                         	[OK]
> Pluto ipsec.conf syntax                           	[OK]
> Hardware random device                            	[N/A]
> Two or more interfaces found, checking IP forwarding	[OK]
> Checking rp_filter                                	[OK]
> Checking that pluto is running                    	[OK]
>  Pluto listening for IKE on udp 500               	[OK]
>  Pluto listening for IKE/NAT-T on udp 4500        	[OK]
>  Pluto ipsec.secret syntax                        	[OK]
> Checking 'ip' command                             	[OK]
> Checking 'iptables' command                       	[OK]
> Checking 'prelink' command does not interfere with FIPSChecking for obsolete ipsec.conf options          	[OK]
> Opportunistic Encryption                          	[DISABLED]

系统是 ubuntu 16.04。

**Comment by larryisthere** [comment] 2016-09-21 07:14
referred to [this](https://github.com/hwdsl2/setup-ipsec-vpn/issues/39) issue, I changed the ip address in /etc/iptables.rules by run:
`vi /etc/iptables.rules`
and run this:
`iptables-restore < /etc/iptables.rules`
to activate it.
And now it works.

This is caused by the ip has changed after the first time I setup the vpn and the script didn't modify this ip address first second time I ran it.

Maybe it's a flaw to improve?

**Comment by hwdsl2** [comment] 2016-09-21 07:40
@larryisthere Thank you for the detailed report. Yes you are correct that the script will not update the IPTables rules if you run it again after the server's IP has changed. For this particular use case, at this time you have to manually update your IP in the NAT table of `/etc/iptables.rules` (and/or `/etc/iptables/rules.v4`, if it exists) and run `iptables-restore`. When I have more time I plan to look into how to improve this behavior.

**Comment by zebozhuang** [comment] 2016-11-18 14:43
@hwdsl2 Thanks for your solution. Did you figure out how to update the ip automatically?

**Comment by hwdsl2** [comment] 2016-11-18 15:06
@zebozhuang This issue had been resolved in commit 7cdd372. If your server IP changes, you must run the VPN setup script again. It will update the IPTables rules for you.

**Comment by zebozhuang** [comment] 2016-11-19 00:41
@hwdsl2 Thanks.
