### ISSUE TITLE
Random disconnects from vpn

### ISSUE THREAD

**Issue by strk1204** [hwdsl2/setup-ipsec-vpn#21] opened 2016-05-17 21:37 UTC
As I browse on my iPad (have had this issue before on other devices) the vpn just disconnects randomly. I was wondering if this may be related to the session time and if so, how can I increase the length of a single session time. Thanks.

**Comment by hwdsl2** [comment] 2016-05-17 21:51
@strk1204 There is no setting on the VPN server related to the total session time. iPhones (and iPads) will disconnect from WiFi (and VPN) when the screen goes to sleep [1]. Apple said that this behavior is by design.

You may also try to tweak the "Dead Peer Detection" settings in `/etc/ipsec.conf`. It is called `dpdtimeout` (search `dpd` within [2]). Edit `ipsec.conf`, increase that value, then run `service ipsec restart`. Now re-connect the VPN.

[1]: https://www.reddit.com/r/apple/comments/1ni89b/ipad_disconnects_from_internet_every_time_i_turn/
[2]: https://libreswan.org/man/ipsec.conf.5.html

**Comment by strk1204** [comment] 2016-05-17 22:59
When the problem occurs, (disconnection) im generally reading through a web page with (i asume) no data transfers being made. Ill give your suggestion a try later tonight. Also, when I use Xauth (IPSec) on my Android 6.0.1 device, it connects but the DNS server timesout, and when I specify a DNS server, it just hangs on loading.

**Comment by hwdsl2** [comment] 2016-05-17 23:05
@strk1204 Android 6 (Marshmallow) has a known bug with its SHA2 implementation [1]. To work around it for `IPsec/XAUTH`, add a line `sha2-truncbug=yes` under the `xauth-psk` section in `ipsec.conf`. Indent lines with two spaces. Then restart ipsec service. For `IPsec/L2TP` please refer to the important notes section in README.

[1] https://libreswan.org/wiki/FAQ#Android_6.0_connection_comes_up_but_no_packet_flow

**Comment by strk1204** [comment] 2016-05-17 23:34
I did read this on your page, but last time I tried it, it broke the VPN on the iOS side.

**Comment by hwdsl2** [comment] 2016-05-20 22:34
Closing this issue for now. Feel free to reply if the problem still persists.

**Closed by hwdsl2** 2016-05-20 22:34 UTC
