### ISSUE TITLE
Unable to Access Servers on local Network

### ISSUE THREAD

**Issue by skystebnicki** [hwdsl2/setup-ipsec-vpn#840] opened 2020-08-25 23:10 UTC
This script is amazing! Thank you.

I am able to connect to the VPN server just fine. I can ping the public interface on the vpn sever, and the private interface from my client machine.

However, if I try to ping another server on my private network, then it fails. I'm sure I just need to tweak something in my routing, but I'm better at coding that networking :)

VPN Server:
- Public IP eth0: 216.x.x.x
- Private IP eth1: 10.x.x.x 

Server2 on VPN Network:
- Private IP: 10.x.x.x

How can I connected through the public IP on the VPN server, then access the private IP of Server2 through the VPN? Is that possible?

**Comment by hwdsl2** [comment] 2020-08-26 04:03
@skystebnicki Hello! I understand that you want the VPN client to access another server on the private network while connected to the VPN. This use case was tested before and worked fine in my tests, with the default IPTables rules added by the VPN setup scripts.

Therefore, the issue is most likely due to your Server2 having firewall rules (e.g. IPTables) that block traffic from your VPN server. You may use e.g. `tcpdump` [1] on Server2 to check if this is the case. I'm closing this issue, but if you have any findings or additional questions, feel free to reply here.

[1] https://linux.die.net/man/8/tcpdump

**Closed by hwdsl2** 2020-08-26 04:03 UTC

**Comment by skystebnicki** [comment] 2020-08-26 15:37
Thank you so much for your help! For the sake of testing, I have turned off the router on Server2.

Here are my iptables rules applied to the VPN:
`
*nat
# VPN
-A POSTROUTING -s 192.168.42.0/24 -o eno1 -j MASQUERADE
-A POSTROUTING -s 192.168.43.0/24 -o eno1 -m policy --dir out --pol none -j MASQUERADE
COMMIT

*filter
# VPN
-A INPUT -p udp -m udp --dport 1701 -m policy --dir in --pol none -j DROP
-A INPUT -m conntrack --ctstate INVALID -j DROP
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p udp -m multiport --dports 500,4500 -j ACCEPT
-A INPUT -p udp -m udp --dport 1701 -m policy --dir in --pol ipsec -j ACCEPT
-A INPUT -p udp -m udp --dport 1701 -j DROP

# Allows all loopback (lo0) traffic and drop all traffic to 127/8 that doesn't use lo0
-A INPUT -i lo -j ACCEPT
-A INPUT ! -i lo -d 127.0.0.0/8 -j REJECT

# Accepts all established inbound connections
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

# Allows SSH connections 
# The --dport number is the same as in /etc/ssh/sshd_config
-A INPUT -p tcp -m state --state NEW --dport 22 -j ACCEPT

# Allow all input from our private network
-A INPUT -s 10.13.96.0/19 -j ACCEPT

# Allow ping
#  note that blocking other types of icmp packets is considered a bad idea by some
#  remove -m icmp --icmp-type 8 from this line to allow all kinds of icmp:
#  https://security.stackexchange.com/questions/22711
-A INPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT

# log iptables denied calls (access via 'dmesg' command)
-A INPUT -m limit --limit 5/min -j LOG --log-prefix "iptables denied: " --log-level 7

# Reject all other inbound - default deny unless explicitly allowed policy:
-A INPUT -j REJECT

# VPN - settngs required for xauth/ipsec VPN
-A FORWARD -m conntrack --ctstate INVALID -j DROP
-A FORWARD -i eno1 -o ppp+ -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i ppp+ -o eno1 -j ACCEPT
-A FORWARD -s 192.168.42.0/24 -d 192.168.42.0/24 -i ppp+ -o ppp+ -j ACCEPT
-A FORWARD -d 192.168.43.0/24 -i eno1 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 192.168.43.0/24 -o eno1 -j ACCEPT

# Reject all other inbound - default deny unless explicitly allowed policy:
-A FORWARD -j REJECT

# Allows all outbound traffic
-A OUTPUT -j ACCEPT

COMMIT
# end of rules
`
VPN route:
`
default via 216.245.198.61 dev eno1
10.0.0.0/8 via 10.4.31.13 dev eno2
10.4.31.12/30 dev eno2 proto kernel scope link src 10.4.31.14
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
172.18.0.0/16 dev docker_gwbridge proto kernel scope link src 172.18.0.1
216.245.198.60/30 dev eno1 proto kernel scope link src 216.245.198.62
`
If I try to ping from VPN server to Server2, here is the tcpdump from Server2:
`tcpdump -i eth0 icmp
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
14:57:37.833549 IP 10.4.31.14 > 10.13.96.71: ICMP echo request, id 6447, seq 0, length 64
14:57:37.833598 IP 10.13.96.71 > 10.4.31.14: ICMP echo reply, id 6447, seq 0, length 64
14:57:38.834608 IP 10.4.31.14 > 10.13.96.71: ICMP echo request, id 6447, seq 1, length 64
14:57:38.834654 IP 10.13.96.71 > 10.4.31.14: ICMP echo reply, id 6447, seq 1, length 64
14:57:39.835596 IP 10.4.31.14 > 10.13.96.71: ICMP echo request, id 6447, seq 2, length 64
14:57:39.835641 IP 10.13.96.71 > 10.4.31.14: ICMP echo reply, id 6447, seq 2, length 64
14:57:40.836642 IP 10.4.31.14 > 10.13.96.71: ICMP echo request, id 6447, seq 3, length 64
14:57:40.836688 IP 10.13.96.71 > 10.4.31.14: ICMP echo reply, id 6447, seq 3, length 64`

If I try to ping from a connected client there is nothing in the tcpdump - never makes it to Server2. But I am getting this odd error on the client terminal - looks like it is trying to do some sort of reverse looking on the public interface?
`sky@MacBook-Pro ~ % ping 10.13.96.71
PING 10.13.96.71 (10.13.96.71): 56 data bytes
92 bytes from 62-198-245-216.static.reverse.lstn.net (216.245.198.62): Destination Port Unreachable
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 5400 b62a   0 0000  3f  01 6f78 192.168.43.10  10.13.96.71

Request timeout for icmp_seq 0
92 bytes from 62-198-245-216.static.reverse.lstn.net (216.245.198.62): Destination Port Unreachable
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 5400 596e   0 0000  3f  01 cc34 192.168.43.10  10.13.96.71`

I'll keep trying to troubleshoot, but if you see anything obvious there your help is very appreciated!

**Comment by skystebnicki** [comment] 2020-08-26 17:02
Ok, through some good old fashioned brute force of trial and error, I found that adding the following rules fixed my problem (adding the second/private/internal nic)

-A POSTROUTING -s 192.168.42.0/24 -o eno2 -j MASQUERADE
-A POSTROUTING -s 192.168.43.0/24 -o eno2 -m policy --dir out --pol none -j MASQUERADE

**Comment by hwdsl2** [comment] 2020-08-27 03:05
@skystebnicki Thanks for the updates!

**Comment by Luccio96** [comment] 2020-12-31 12:33
@skystebnicki Can you please explain how do you solve the problem? I have the same issue

**Comment by ShibalovRoman** [comment] 2023-03-22 15:44
This is still actual problem. I didn't found any work solve. @hwdsl2 can you please help with absolutely the same problem - I connect to server1 and can't ping from client server2 which is in one local network with server1?
