### ISSUE TITLE
无法通过vpn上网

### ISSUE THREAD

**Issue by Rehtt** [hwdsl2/setup-ipsec-vpn#188] opened 2017-08-13 09:07 UTC
linux下按照教程设置客户端，可这几天无法通过vpn上网，在android,windows可以正常上网，地址密码那些检查过都是正确的。

**Comment by hwdsl2** [comment] 2017-08-13 17:36
@Rehtt Try restarting services on the VPN server:

```
sudo service ipsec restart
sudo service xl2tpd restart
```

Then reboot your VPN client device (Linux). Finally, retry the connection by following the steps in [1]. If it still does not work, then the issue is probably with your network.

As this is not an issue with the VPN script itself, I am closing this. Any further questions can be asked on the Libreswan users mailing list [2].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#linux
[2] https://lists.libreswan.org/mailman/listinfo/swan

**Closed by hwdsl2** 2017-08-13 17:36 UTC
