### ISSUE TITLE
Unable to browse certain sites

### ISSUE THREAD

**Issue by KBapna** [hwdsl2/setup-ipsec-vpn#1315] opened 2023-01-13 19:21 UTC
Hey,

I have encountered a problem where I am unable to browse certain sites on VPN.

My setup is that I have multiple VMs behind OPNsense firewall and I am able to browse everything from those machines without any problem.

One of those VM is a VPN Server (Previledged CT) and I have installed Installed Ikev2 VPN on it. When I browse certain sites for e.g. : techpowerup.com it keeps loading for eternity, but on another tab I can browse almost any site without any problem.

DNS check :

<code>nslookup techpowerup.com</code>
<output>
Server:  VPN.proxmox.local
Address:  172.25.0.3

Non-authoritative answer:
Name:    techpowerup.com
Address:  138.199.40.9
</output>

I cant seem to figure out the issue Also I have checked and troubleshoot the following but they seem to work fine
1) Firewall (OPNsense)
2) DNS server (nslookup gives response)
3) Ping (Works as expected)

BTW I have checked that these sites work if VPN is setup on online hosting providers, So there might be something that I have messed up but again, if it is so than I should not be able to browse most of the sites.

**Comment by hwdsl2** [comment] 2023-01-14 04:20
@KBapna Hello! First, for proxmox, it is recommended to create a fully virtualized VM (not CT) for the VPN server, although this may not be related to this issue. The issue you described sounds like an MTU/MSS problem. Please refer to:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android-mtumss-issues

In addition, you may use `ifconfig` to check and fix the MTU size on your VPN server (the CT you mentioned). Please refer to:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#cannot-open-websites-after-connecting-to-ikev2

**Comment by KBapna** [comment] 2023-01-14 09:12
Hey! thanks for the response.
I also checked MTU earlier and it is set to 1500 everywhere but still it gives error site took too long to respond.

**Comment by hwdsl2** [comment] 2023-01-15 20:56
@KBapna Did you try the fix in MTU/MSS section?
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android-mtumss-issues

**Comment by hwdsl2** [comment] 2023-01-16 02:31
@KBapna Please try the MTU/MSS fix mentioned above. Based on your comments, this is most likely an issue with your particular server environment (VMs in Proxmox), and not an issue with the VPN script itself.

For this reason, I'll close this but you are welcome to continue the discussion here if you have new information.

**Closed** 2023-01-16 02:31 UTC

**Comment by KBapna** [comment] 2023-01-16 06:34
@hwdsl2
I attempted this fix for the issue, but it was unsuccessful. I am willing to provide any additional information that may be necessary for a resolution.

**Comment by hwdsl2** [comment] 2023-01-16 07:23
@KBapna Yes, that could be a possible reason. Lowering the MTU/MSS value could help, as mentioned in [this troubleshooting section](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android-mtumss-issues). I assume you already tried that. Those commands should be run inside the Proxmox CT (i.e. the VPN server in your use case).

**Comment by KBapna** [comment] 2023-01-16 11:33
@hwdsl2 
I am facing this issue on both Android and Windows devices. I have already tried these steps such as lowering the MTU to 1000 on VPN server, Also I have tried allowing jumbo frames on opnsense with an MTU of 1500 on the VPN, but neither of these have resolved the issue. Can you suggest any other steps I can try to resolve this issue?

**Comment by hwdsl2** [comment] 2023-01-16 15:17
@KBapna The MTU should be increased to 1500, not set to a lower value. Unfortunately, I don't have further suggestions for troubleshooting this. You can troubleshoot further yourself and see if you can find the root cause.

**Comment by KBapna** [comment] 2023-01-26 20:39
@hwdsl2 
I think I have narrowed down the problem that the VPN doesn't auto defragment the packets. I tries a few other VPN and they do defragment packets of size 9000 but in my use case the protocol I want to use is IKEv2, for which your VPN is best but this I can't use it if packages are not automatically defragmented.

off-topic:
1) While deleting VPN connections it doesn't revoke them automatically. As if someone wants to delete a connection, wouldn't it be great if it also revokes the connection as well?
I know its just one step to revoke but if you forget, than it saves the hassle of the workaround to revoke it.
2) Also it would be great to add an option to add months for VPN client once it has been created as it saves the time to set it up and deploy again.

**Comment by hwdsl2** [comment] 2023-01-27 11:55
@KBapna Setting the MTU to a higher value ([reference](https://www.networkworld.com/article/2224654/mtu-size-issues.html)) might help prevent packet fragmentation. The commands in the [Android MTU/MSS issues](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android-mtumss-issues) section might help too, but I think you've already tried that.

Thank you for your suggestions, they will be considered for future improvements.
1.  As you said, currently deleting an IKEv2 client on the VPN server does not automatically revoke the corresponding certificate. This was intended for the use cases where the user wants to simply remove some IKEv2 clients that was created earlier. 
2. Currently, IKEv2 client certificates expire in 120 months (10 years) by default, so this is not an issue for common use cases. Extending the expiration date of an existing IKEv2 client certificate would require generating a new certificate and importing it into the VPN client.

**Comment by KBapna** [comment] 2023-01-27 12:49
@hwdsl2 
I tried setting MTU to 9000 with 
<code>sudo ifconfig eno1 mtu 9000</code>
but it didn't help as incoming packets are way larger.

Below I have tried to explain the connection

PC--1400-->VPN--1500-->router -->internet              works
internet-->router--1500-->VPN--1400(fails)-->PC      fails as packet is too large

The possible solution I came up with was that the VPN could defragment the packets to smaller size so they are not dropped.
But I don't know how to implement it.

Suggestions (OFF-Topic):
1) Are you referring to expired clients here?
2) For some use cases there is a need to create a client for fewer months and extend them if necessary. So if I created a client for 1 month and want to extend it further, it would be great to extend it instead of setting it up again on there computer.
Also, there can be an option to extend a expired client tenure if possible for the same.

**Comment by hwdsl2** [comment] 2023-01-27 14:16
@KBapna For (1) my comment was not limited to expired clients, but IKEv2 clients in general. Not sure about a good solution to the fragmentation issue you mentioned.

**Comment by KBapna** [comment] 2023-01-29 00:24
@hwdsl2 
I made a new VPN from scratch on VM and it seems to work but changing DNS gives the same problem.
Could you provide the steps from start for my requirements as I have tries all combinations I can, and they don't work. Thanks.

IKEV2 only mode
Network - 172.25.2.0/24 (172.25.2.1-172.25.2.199 are static assignments)
Address - 172.25.2.200-172.25.2.254
DNS - 172.25.0.3

rc.local (to route networks. Context: #1304 but IPs are changed)

netif=$(route 2>/dev/null | grep -m 1 '^default' | grep -o '[^ ]*$')
iptables -I FORWARD 2 -i "$netif" -o ppp+ -s 172.25.0.0/22 -j ACCEPT
iptables -I FORWARD 2 -i "$netif" -d 172.25.2.0/24 -s 172.25.0.0/22 -j ACCEPT
